[package]
name = "simconnect-client"
version = "0.1.0"
authors = ["Mihai Dinculescu <mihai.dinculescu@outlook.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.58"

[dependencies]
num_enum = "0.5"
tracing = "0.1"
