name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust_checks:
    name: "Checks"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: tauri-cli
          version: 1.1.1
          use-tool-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn install
        working-directory: ./www
        run: yarn install
      - name: Yarn build
        working-directory: ./www
        run: yarn build
      - name: Run format
        run: cargo make format
      - name: Run check
        run: cargo make check
      - name: Run clippy
        run: cargo make clippy
      - name: Run test
        run: cargo make test
      - name: Run tauri info
        run: cargo tauri info
      - name: Run tauri build
        run: cargo tauri build
